### ISSUE TITLE
demo bug

### ISSUE THREAD

**Issue by DmitryEfimenko** [orizens/ngx-youtube-player#1]
Buttons Play/Pause are not clickable.
The issue is due to `<h2>` tag overlaying the buttons. See screenshot:
![ng2-youtube-bug](https://cloud.githubusercontent.com/assets/2098175/19402095/eaccb5fa-9213-11e6-8810-22448e35f6aa.jpg)

**Comment by orizens** [comment]
hi.
still - i don't experience this in mac, latest chrome.
I updated the demo with a different markup - please check.

**Comment by DmitryEfimenko** [comment]
you have class `col-sm-12` on the buttons' wrapping div. It hides the buttons on larger screen. Just get rid of it.

**Comment by orizens** [comment]
hi @DmitryEfimenko 
i updated the class to be with "col-md-12".
please confirm it's working.
Thanks.

**Comment by DmitryEfimenko** [comment]
it works
