### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by sudhirroy-tudip** [orizens/ngx-youtube-player#14]
Hi,
I am implementing this in Angular2 typescript. Actually, I have facebook like web application in which lot's of youtube player are in single page. I am getting this error every time while it opens. I am using in localhost but it also appears on server (xyz.com). Please help me out? 

Any help is greatly appreciated.

**Comment by jdmaldonado** [comment]
I have the same issue
maybe is related with this case... https://goo.gl/HtYJQt  but i'm not sure, and i don't know how fix it.

Does someone know how fix it ?

**Comment by mayrascript** [comment]
I have the same issue

**Comment by aleixsuau** [comment]
Hi @sudhirroy-tudip ,
How did you solve it?
Thanks!

**Comment by marslan2037** [comment]
why this is closed? the issue is still remains

**Comment by orizens** [comment]
The issue is within YouTube player

**Comment by marslan2037** [comment]
@orizens how i can fix it ?
