### ISSUE TITLE
repeatedly requests on remote.js

### ISSUE THREAD

**Issue by tobiasetter** [orizens/ngx-youtube-player#15]
Hi

I am developping an angular 2 typescript application.
If I open browser network tools I see that remote.js is called all seconds or multiple times a second. And it does not stop!

How can I fix that?

Many thanks!

**Comment by orizens** [comment]
remote.js is called from within the youtube's player. i think it's internal implementation and error - which doesn't carried on to the app that is using the component (as in http://echoesplayer.com)
