### ISSUE TITLE
onready event doesnt fire when lazyloaded module is involved

### ISSUE THREAD

**Issue by maystorm74** [orizens/ngx-youtube-player#18]
I have youtube-player component implemented in my eagerly loaded HomeComponent and a lazyloaded module. if onready event fires in a eagerly loaded component it won't be able to fire in a lazy loaded module.
And vice versa if it fires in a lazy loaded module it won't be able to fire in an eagerly loaded component afterwards. 

I then transformed the module to eagerly loaded and it all started working but the issue still stands.

**Comment by orizens** [comment]
hi @maystorm74 
the onready supposed to be called once in order to interact with the actual YT instance to have more control.

**Comment by orizens** [comment]
hi @maystorm74 
have you resolved the issue?
if not - can you please share a plunkr showing the issue?

**Comment by ludovicfourrage** [comment]
Hello, I'm experiencing the same issue with Ionic 3 - Angular 5. Do you have a fix for this by any chance?
@maystorm74 I'm not sure how to go from lazy loaded to eagerly loaded- I'm using youtube in a ionic component on 2 seperate pages. Thank you!

**Comment by orizens** [comment]
hi @orizens 
can you please share a stackblitz showing the issue?
