### ISSUE TITLE
Property 'getVideoData' does not exist on type 'Player'

### ISSUE THREAD

**Issue by tagniam** [orizens/ngx-youtube-player#20]
Hi, for some reason I can call methods like `playVideo()` and `seekTo()`, but `getVideoData()` doesn't work on my local machine. Calling the method on the Plunker demo works fine.

I have `@types/youtube` installed if that's relevant.

**Comment by tagniam** [comment]
Sorry, it appears `getVideoData()` is deprecated.

The new way to get a video's name and author is to parse the string from `http://www.youtube.com/get_video_info?video_id={id}`, if anyone was having the same problem.

**Comment by soromamadou** [comment]
you can use preview version of @types/youtube: 0.0.28  it still working. But in the latest at this moment there is not type for getVideoData(). hope this help.
