### ISSUE TITLE
Namespace 'YT' has no exported member 'PlayerEvent'

### ISSUE THREAD

**Issue by fabiolima** [orizens/ngx-youtube-player#21]
After following the tutorial steps to install and use, I got  the missing type error solved in this issue https://github.com/orizens/ng2-youtube-player/issues/4

And now I got this error with YT.PlayerEvent.

could you help me please? (and sorry for my english)

Node version: 6.10.2
npm version: 3.10.10
Angular 4

**Comment by orizens** [comment]
hi @fabiolima 
i upgraded the package with - "@types/youtube": "0.0.29".

**Comment by explooosion** [comment]
`npm i @types/youtube@0.0.29`

Angular4 - success

thanks 👍
