### ISSUE TITLE
how to show a bunch of videos in one page

### ISSUE THREAD

**Issue by adaror** [orizens/ngx-youtube-player#22]
hey,
i am trying to show a few videos in one page using ngFor
but the buttons are just working for the first video i choose to play.
i tried to create an array of players but it still not working.
any idea?

**Comment by orizens** [comment]
hi @adaror 
you should save the "player" (with the ```(ready)``` event) object for each video in order to add customized buttons for each video.
```
<youtube-player
   (ready)="savePlayer($event)">
</youtube-player>
```
