### ISSUE TITLE
Bug - script element added for each player instance

### ISSUE THREAD

**Issue by gs-scooter** [orizens/ngx-youtube-player#27]
If you have a page that declares more than one instance of the player, each instance will append a script element node to the root document body for adding the YouTube iFrame API reference. This occurs in loadPlayerApi() each time a new player is set up.

There should only ever be one script element for the reference that gets added if it doesn't already exist.

Please advise when this could be addressed.

**Comment by gs-scooter** [comment]
Just checking in to see if there is any progress/update on this. 

Thanks.

**Comment by orizens** [comment]
checking..

**Comment by orizens** [comment]
fixed by https://github.com/orizens/ng2-youtube-player/commit/8faac39a09016da87ec504261f55e2abc8097e4b
