### ISSUE TITLE
make player fullscreen onclick of custom fullscreen button

### ISSUE THREAD

**Issue by lakhank295** [orizens/ngx-youtube-player#28]
hello,
i am using this package in my angular 2 project. but i have one issue that is i want to make my video player fullscreen & exit of fullscreen on custom fullscreen button. i am not getting any idea from youtube API Doc. please give some suggestion that how can i implement this.

**Comment by orizens** [comment]
hi @lakhank143 - this requires further development and not part of this free component.
you can contact me at: http://orizens.com/contact
