### ISSUE TITLE
https iframe_api

### ISSUE THREAD

**Issue by tagazok** [orizens/ngx-youtube-player#3]
Hi,
Very nice component! Although, I had to run manually "npm i @types/youtube" as it did not find the typings.

I am hosting most of my projects on github using gh-pages and non-ssl requests are not permitted.
Could it be possible to the https url for the iframe_api ?
http://www.youtube.com/iframe_api => https://www.youtube.com/iframe_api

Thanks :)

**Comment by NatsuOnFire** [comment]
Hi, 
I did a pull request to correct this problem: https://github.com/orizens/ng2-youtube-player/pull/6

**Comment by tarlepp** [comment]
Why this isn't merged ?

**Comment by tarlepp** [comment]
^up
