### ISSUE TITLE
plugin not working for ionic

### ISSUE THREAD

**Issue by VlnRbn** [orizens/ngx-youtube-player#30]
like in #24 making changes in package.json didn't work for me.
In chrome inspect im getting this :
 Failed to load resource: net::ERR_FILE_NOT_FOUND file://www.youtube.com/iframe_api
need help..please

**Comment by VlnRbn** [comment]
the issue fixed by adding this in index.html

`  <script>
    console.log("script loaded")
    if (!window['YT']) { var YT = { loading: 0, loaded: 0 }; } if (!window['YTConfig']) { var YTConfig = { 'host': 'http://www.youtube.com' }; } if (!YT.loading) { YT.loading = 1; (function () { var l = []; YT.ready = function (f) { if (YT.loaded) { f(); } else { l.push(f); } }; window.onYTReady = function () { YT.loaded = 1; for (var i = 0; i < l.length; i++) { try { l[i](); } catch (e) { } } }; YT.setConfig = function (c) { for (var k in c) { if (c.hasOwnProperty(k)) { YTConfig[k] = c[k]; } } }; var a = document.createElement('script'); a.type = 'text/javascript'; a.id = 'www-widgetapi-script'; a.src = 'https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl-P7Nkv/www-widgetapi.js'; a.async = true; var b = document.getElementsByTagName('script')[0]; b.parentNode.insertBefore(a, b); })(); }
  </script>`

**Comment by codinronan** [comment]
The above script is not necessary, the component provides a way to do this out of the box. It receives a `[protocol]` input that you can assign on the component:

`<youtube-player protocol="http" ...>` 

Setting that will make it work anywhere. Obviously if you are running this from an actual website that is https you'd take care of that in that way. You can data bind it if you want too:

`<youtube-player [protocol]="yourVarOrFuncThatDecidesProtocol" ...>`
