### ISSUE TITLE
The selector "#yt-player-ngx-component" did not match any elements

### ISSUE THREAD

**Issue by stephencawood** [orizens/ngx-youtube-player#31]
Have you ever come across this error? The element is there, but I'm seeing this error in some cases. 

Error: The selector "..." did not match any elements
    at DefaultDomRenderer2.selectRootElement (platform-browser.js:2791)
    at BaseAnimationRenderer.selectRootElement (animations.js:502)
    at DebugRenderer2.selectRootElement (core.js:14962)
    at YoutubePlayerComponent.ngAfterContentInit (youtube.component.ts:49)
    at callProviderLifecycles (core.js:12421)
    at callElementProvidersLifecycles (core.js:12398)
    at callLifecycleHooksChildrenFirst (core.js:12382)
    at checkAndUpdateView (core.js:13510)
    at callViewAction (core.js:13857)
    at execComponentViewsAction (core.js:13789)

**Comment by hcabnehca** [comment]
Hey @stephencawood , 
I am also running into this issue. Did you close it because you encountered a solution?
If so, I'd be happy to hear about it - thanks!

**Comment by stephencawood** [comment]
I believe I closed it because I realized the issue was on my side. Sorry, not much help.

**Comment by mootech** [comment]
It happens when I put the video-player under mat-card-content. Otherwise, it is fine.
 <mat-card-content>
  <youtube-player
    [videoId]="id"
    (ready)="savePlayer($event)"
    (change)="onStateChange($event)"
  >
  </youtube-player>
  </mat-card-content>

**Comment by arcovoltaico** [comment]
If I create the component dynamically (inside a container <template>) it's giving me this error...

**Comment by lova-mada** [comment]
Hi all,
I have the same issue when I put a player in a hidden slide (ngx slick).
Any idea?

**Comment by lova-mada** [comment]
ok, I found the solution

**Comment by igorissen** [comment]
@lova-mada and the solution is ?

**Comment by tagazok** [comment]
I would also be interested in the solution @lova-mada :)

**Comment by dzunglean** [comment]
I have same issue with Mat-tab module and solved with lazy load option

**Comment by yehorovvlad** [comment]
Fixed by adding ngAfterViewInit function:

<youtube-player *ngIf="afterViewInit"  ...some options... </youtube-player>

import { Component, AfterViewInit } from "@angular/core";

@Component({
  selector: "app-video",
  templateUrl: "./video.component.html",
  styleUrls: ["./video.component.scss"]
})
export class VideoComponent implements AfterViewInit {
 afterViewInit: boolean;

  ngAfterViewInit() {
    this.afterViewInit= true;
  }
}

**Comment by meet0929** [comment]
remove from app.module file 
```
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
platformBrowserDynamic().bootstrapModule(AppModule);
```


it works for me

**Comment by AnnaAlexandrovna** [comment]
Lazy loading help me
https://material.angular.io/components/tabs/overview
```
<ng-template matTabContent>
          Content 1 - Loaded: {{getTimeLoaded(1) | date:'medium'}}
          <youtube-player
            [videoId]="id"
            (ready)="savePlayer($event)"
            (change)="onStateChange($event)"
          ></youtube-player>
        </ng-template>
```
