### ISSUE TITLE
Trouble with timeupdate event

### ISSUE THREAD

**Issue by amialkumau** [orizens/ngx-youtube-player#34]
Hello! I've got some problems with timeupdate event for my own time progressbar ( I disabled youtube controls). I add inside `onReady` following code:
```
onReady (player) {
    this.player = player;
    this.player.addEventListener('timeupdate', this.updateProgressBar, true);
  }
```
and `updateProgressBar` method
```
  updateProgressBar() {
      this.progressBar.nativeElement.value = Math.floor((100 / this.player.getDuration()) * this.player.getCurrentTime());
  }
```
And timeupdate event doesn't fire.  What am I doing wrong?

**Comment by orizens** [comment]
this is a youtube player related issue.
reopen if still relevant to ngx-youtube-player.
