### ISSUE TITLE
Doesn't seem to work on iOS (Ionic 3)

### ISSUE THREAD

**Issue by imperatormk** [orizens/ngx-youtube-player#37]
Let me preface this by saying that I am not able to further elaborate on the issue since the device I'm trying this on is remote, but using the exactly same code for my Ionic 3 app on Android and iOS, Android works well, iOS doesn't. The video never loads. Hope someone can try to reproduce this and shed some light on what could go wrong.

Thanks!

**Comment by orizens** [comment]
ios had issues with embedding youtube - nothing i can do.

**Comment by imperatormk** [comment]
Managed to embed a video with some vanilla code so there might be a way :)
