### ISSUE TITLE
Multiple videos

### ISSUE THREAD

**Issue by rahulkumarshaw1** [orizens/ngx-youtube-player#39]
Can this package be used for displaying multiple videos ?? 
 I need a carousel of videos. Can this package be used???
if yes, then how to pass multiple video id to input [videoId] ????

**Comment by orizens** [comment]
this a component for a single video only.

**Comment by immannino** [comment]
You can create multiple instances of the object. Not necessarily efficient, but it works. [Demo](https://immannino.github.io/super-dumb-youtube-grid/)

**Comment by rahulkumarshaw1** [comment]
Sorry, I forgot to close this issue. I'm already using this package to display carousel of youtube videos.
Tq guys
