### ISSUE TITLE
Video frame doesn't show up on first load or hard reset

### ISSUE THREAD

**Issue by ekstremedia** [orizens/ngx-youtube-player#41]
I have an issue where the first time I load my app, the video don't show up at all. If i hit refresh, it shows up as normal. But if i then do a hard reset, shift+f5, its not showing up again. This in the Chrome browser, Edge seems to be working fine. I check in the code inspector when its not showing up, but the <youtube-player> tags are there even if its not showing up. Any ideas here? Source: https://github.com/ekstremedia/angular6/blob/master/src/app/video/video/video.component.html

**Comment by ekstremedia** [comment]
It appears that I had this in my index.html and when **removing** it, the issue disappeared:
  <script src='https://www.youtube.com/iframe_api'></script>

**Comment by JishnaJyothi** [comment]
I am also facing the same issue is there any solution . i am not having <script src='https://www.youtube.com/iframe_api'></script> in my index.html still facing the issue
