### ISSUE TITLE
Impossible to display settings (gear) icon 

### ISSUE THREAD

**Issue by pcolagrosso** [orizens/ngx-youtube-player#43]
I have used the ngx-youtube-player component in a variety of contexts, and I am finding that the resulting player never has the 'gear' icon which makes it possible to control parameters such as speed, subtitles, etc...

This is the same behavior as the online stackblitz demo:  https://stackblitz.com/edit/ngx-youtube-player?file=src%2Fapp%2Fapp.module.ts.

I have tried to use the "playerVar" parameters to change this behavior. 

For example, using the following code in my HTML file I can turn off all the controls:  (as a result of 'controls: 0):   

<youtube-player [videoId]="currentVideoId" [height]="playerHeight" [width]="playerWidth"
[playerVars]="{ 'controls':'0'}"
(ready)="savePlayer($event)" (change)="onStateChange($event)">
</youtube-player>

Using the following variation in my HTML file I can turn the controls back on:

<youtube-player [videoId]="currentVideoId" [height]="playerHeight" [width]="playerWidth"
[playerVars]="{ 'controls':'1'}"
(ready)="savePlayer($event)" (change)="onStateChange($event)">
</youtube-player

Based on the "player parameters" reference (https://developers.google.com/youtube/player_parameters?playerVersion=HTML5)  there is no way to turn individual controls on or off.

If I open in Youtube the same video as in the stacklitz demo, then I do get the gear icon:

       https://www.youtube.com/watch?v=qDuKsiwS5xw&feature=youtu.be

If I look at the online Youtube API live demo (https://developers.google.com/youtube/youtube_player_demo),  I am also finding that the "gear" icon is always present (except if you "uncheck" the "controls" parameter.

This therefore appears to be a bug with ngx-youtube-player component.

**Comment by orizens** [comment]
this component is using the iframe player api. 
for the gear icon to appear - i think the player size should be bigger then the defaults that are set with this one.
