### ISSUE TITLE
can't hide "more videos element"

### ISSUE THREAD

**Issue by amilkarferra** [orizens/ngx-youtube-player#45]
Hello, thanks for such a good player!  is there a way to remove the more videos elements on the player when the video is pause or stop ????

**Comment by orizens** [comment]
you may want to consult with https://developers.google.com/youtube/player_parameters

**Comment by amilkarferra** [comment]
Ok thanks, but can i pass those paramters to your ngx-youtube-player??? 
Thanks again for your answer

**Comment by orizens** [comment]
yes - consult the source code or docs

**Comment by amilkarferra** [comment]
ok super thanks
