### ISSUE TITLE
Angular Universal fail

### ISSUE THREAD

**Issue by derschnee68** [orizens/ngx-youtube-player#46]
**How to reproduce**
- Insert youtube-player component into page.
- Build and serve universal, go to page

**Error**
window is not defined, in YoutubePlayerService (line 9)
``
export function win() {
  return window;
}
``

Instead, you should have the classic workaround, and thus, something like
``
if(isPlatformBrowser(this.platformId)) {
 win() // whatever code
}
``

Sorry, I can't do the pull request, but this should be easy to fix.

Thank you

**Comment by orizens** [comment]
@derschnee68 would you be able to test this?

**Comment by orizens** [comment]
@derschnee68 what does the server should get instead of win, global?
