### ISSUE TITLE
Clicking play on the StackBlitz demo doesn't seem to result in the video playing?

### ISSUE THREAD

**Issue by Atticus29** [orizens/ngx-youtube-player#48]
I'm using Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) on a MacBook Air running OS Mojave v.10.14.5.

Video reproduction of the issue here:
https://youtu.be/QRA2JTP3VOs

**Comment by orizens** [comment]
it's not reproducing in my mac and chrome.
perhaps a youtube setting your'e unintentionally using?
