### ISSUE TITLE
Electron build problems

### ISSUE THREAD

**Issue by arcovoltaico** [orizens/ngx-youtube-player#49]
Hi, 
When using it on Electron and not running it as node server, but as a build, the video will fail because the protocol is set to file instead http. I have fixed by hardcoding it from return protocol to return protocol 'http'; And it works. It would be nice to fix it, maybe something like if protocol is 'file' change it to http.

**Comment by orizens** [comment]
hi @arcovoltaico are you able to open a pr?

**Comment by arcovoltaico** [comment]
It's here
https://github.com/orizens/ngx-youtube-player/pull/50/files
But as I can't make npm link working on an angular project
https://stackoverflow.com/questions/45480341/npm-link-is-not-working-with-angular-cli-created-projects.  I'm not sure if it will work properly.
