### ISSUE TITLE
Dropping scarf dependency

### ISSUE THREAD

**Issue by samsch** [orizens/ngx-youtube-player#64]
Heya, we have a community push to get @scarf/scarf removed from packages. It's a data protection and library expectations issue.

There's a considerable backlog of conversation on Reactiflux #news-and-links, with a reasonable starting point here: https://discordapp.com/channels/102860784329052160/105816607976095744/727600754646450206

The conversation also included the author of scarf as well.

The result being tannerlinsley/react-query#676

**Comment by orizens** [comment]
@samsch lib is now using the latest scarfjs (v2) which allows opting out following this setting
https://github.com/scarf-sh/scarf-js#as-a-user-of-a-package-using-scarf-js-how-can-i-opt-out-of-analytics
