### ISSUE TITLE
Angular Universal [As Node]

### ISSUE THREAD

**Issue by jimdrury** [orizens/ngx-youtube-player#8]
Angular Universal seems to be having trouble with this when rendering server side, as it's accessing the DOM through ElementRef and the simply DOM isn't available.

I've worked around this by creating a dummy youtube-player component to satisfy the component's existence for Node, but really you probably should be accessing the DOM through renderer.

**Comment by orizens** [comment]
Hi.
Can you share an example?

**Comment by orizens** [comment]
@JimDrury 
are you referring to [this line](https://github.com/orizens/ng2-youtube-player/blob/5af199375cce68b3251c577a310d0024a1dde2aa/src/youtube-player.component.ts#L33)?

**Comment by jimdrury** [comment]
Sorry for the super late reply, yes i was
