### ISSUE TITLE
Angular 13 video not loading

### ISSUE THREAD

**Issue by nolafs** [orizens/ngx-youtube-player#85]
Hi, 

The video is not loading.

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin (****).

Any idea how to fix this?

Cheers
Olaf

**Comment by orizens** [comment]
hi @nolafs 
follow the readme's demo link and compare with your code.

**Comment by nolafs** [comment]
Thanks, the code is identical but after moving it outside of my ng-template, it works.

**Comment by orizens** [comment]
awesome.
