### ISSUE TITLE
Support for PlayerVars

### ISSUE THREAD

**Issue by jonnydangerous** [orizens/ngx-youtube-player#9]
I can see in the youtube-player.service there is an option for PlayerVars that is commented out. Any chance this will be included soon?

**Comment by digitalcosmos** [comment]
I second @jonnydangerous, PlayerVars are important to customize the player (eg: remove controls)
Thanks for this component @orizens, keep up the good work! :+1:

**Comment by orizens** [comment]
Hi.
Just saw this issue.
I'll look into it soon.

**Comment by ilkkalyyvuo** [comment]
Hi,

Could you provide an example of using playerVars in component? I can't get controls=0 working.

Thanks!

**Comment by tagniam** [comment]
@ilkkalyyvuo This is a bit late, but if you still need an example, here's the way to get controls=0 working:

```
<youtube-player
      [videoId]="id"
      (ready)="savePlayer($event)"
      (change)="onStateChange($event)"
      [playerVars]="{'controls': 0}">
</youtube-player>
```

**Comment by gabfiocchi** [comment]
@tagniam Looking at your comment, I tried to put the value in a public variable from the controller. But this does not work, just respect the values if I set it in the template. Any ideas?
